### ISSUE TITLE
Unsupported Java.  Your build is currently configured to use Java 17.0.8 and Gradle 7.1.

### ISSUE THREAD

**Issue by kazurayam** [bonigarcia/selenium-webdriver-java#729]
I cloned the master branch of https://github.com/bonigarcia/selenium-webdriver-java.
I installed JDK17.0.8 into my macOS 12.7.
I opened the project in IntelliJ IDEA, I got the following error messages in the Build tab:

```
Unsupported Java. 
Your build is currently configured to use Java 17.0.8 and Gradle 7.1.

Possible solution:
 - Use Java 16 as Gradle JVM: Open Gradle settings 
 - Upgrade Gradle wrapper to 7.2 version and re-import the project

```

IntellJ IDEA found Gradle 7.1 to be used, but the Project's JVM is v17.0.8.
It seems that Gradle7.1 is too old to work on JVM 17.

I checked the `gradle/wrapper/gradle-wrapper.properties` of the master branch:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.1-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

The `gradle-wrapper.properties` files specified gradle v7.1 ---- but it must be too old to work on JDK17.

**Comment by bonigarcia** [comment]
I updated the Gradle wrapper to 8.4. Also, I updated all the dependencies in all projects. The build is green again: https://github.com/bonigarcia/selenium-webdriver-java/actions/runs/6711557214
