### ISSUE TITLE
Problem with opening project as a gradle project

### ISSUE THREAD

**Issue by knazw** [bonigarcia/selenium-webdriver-java#758]
Problem with opening project (558f8013cc4b9b4d87d19d7577bc8068e04289ce) as a gradle project.

I opened project as a gradle project in IntelliJ IDEA 2023.2.2 (Community Edition).
But during configuring project ':selenium-webdriver-junit4' a problem occured:

`A problem occurred configuring project ':selenium-webdriver-junit4'.
> Could not resolve all files for configuration ':selenium-webdriver-junit4:classpath'.
   > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:3.1.5.
     Required by:
         project :selenium-webdriver-junit4 > org.springframework.boot:org.springframework.boot.gradle.plugin:3.1.5
      > No matching variant of org.springframework.boot:spring-boot-gradle-plugin:3.1.5 was found. The consumer was configured to find a library for use during runtime, compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.4' but:
          - Variant 'apiElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.1.5 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'javadocElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.1.5 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'mavenOptionalApiElements' capability org.springframework.boot:spring-boot-gradle-plugin-maven-optional:3.1.5 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'mavenOptionalRuntimeElements' capability org.springframework.boot:spring-boot-gradle-plugin-maven-optional:3.1.5 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'runtimeElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.1.5 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
          - Variant 'sourcesElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.1.5 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.4')
                  ...`

I am using jbr-17 (JetBrains Runitime version 17.0.08) and 18 language level.

BR,
knazw

**Comment by kazurayam** [comment]
I guess you have the Preference of your IntelliJ has a problem.

<img width="1094" alt="Screenshot 2023-11-12 at 10 52 19" src="https://github.com/bonigarcia/selenium-webdriver-java/assets/4467417/9ab86c29-2544-4a1c-9d5e-1b87354a48d2">

Open "Preferences > Build, Execution, Deployment > Build Tools > Gradle"
Check "Gradle Projects > Gradle JVM".

Do you have JDK 17 as Gradle JVM? Possibly not.

**Comment by knazw** [comment]
eh you are right, my mistake :)

**Comment by knazw** [comment]
eh you are right, my mistake :)
