### ISSUE TITLE
Opera browser version

### ISSUE THREAD

**Issue by jhagege** [bonigarcia/selenium-webdriver-java#863]
Hi, came across the book, congrats !
Trying to run the tests on Opera, but it shows "Browser opera is not available in the system"
Maybe would be better to run on older version of Opera browser? 

Thanks!

**Comment by bonigarcia** [comment]
Hello, thanks for your message.

I'm afraid Opera is not compatible with the latest version of Selenium. If you try to create an `OperaDriver` object with Selenium 4, you will get an error like this:

```
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Handshake response does not match any supported protocol. 
```

See for instance: https://github.com/bonigarcia/webdrivermanager/issues/1069#issuecomment-1625108546

I believe the only way to driver Opera with Selenium is using an old version of Selenium, e.g. Selenium 3.

**Comment by jhagege** [comment]
Great thanks much

*Joachim Hagege ***@***.***>* Phone - France: +33 6 74 98 64
78

Phone - Israel: +972 52 403 8041
